### ISSUE TITLE
Problem with Screen resolution and zoom in browser when generating pdf file from HTML with JSPDF and Html2Canvas.

### ISSUE THREAD

**Issue by msdian-hub** [johnnywang1994/jsPDF-html2canvas#34]
Hello.

The issue is with the Screen Resolution and Browser size. When I download the PDF from my Browser. The pdf is dependent upon the size of the Browser. Is there a way to fix that

Thanks.

**Comment by johnnywang1994** [comment]
Hi, I'll add a "autoResize" option in order to allow disabling the auto resize feature. The captured image size is now auto resized to fit the PDF layout.
