### ISSUE TITLE
inner function success , this.output is "undefined"

### ISSUE THREAD

**Issue by szjSmiling** [johnnywang1994/jsPDF-html2canvas#38]
version: 1.5.1
html2PDF(exportRef.value, {
    jsPDF: {
      format: 'a4'
    },
    imageType: 'image/jpeg',
    output: 'xxx.pdf',
    success: function (pdf) {
      console.log('...output', this.output);   // undefined
      pdf.save('xxxxx.pdf');
    }
})

**Comment by johnnywang1994** [comment]
@szjSmiling Hi, thanks for reporting the issue, please use v1.5.2 which fixed this issue.
